name: Release

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run standard-version
        run: npx standard-version

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(release): update CHANGELOG"
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/auto-version-update
          title: 'chore(release): release: update version and changelog files'
          body: 'This PR updates CHANGELOG.md with the new version generated by the automated release.'
          base: master
          add-paths: |
            CHANGELOG.md
          delete-branch: true
